### ISSUE TITLE
"Save" button not clickable after editing inputs and outputs

### ISSUE THREAD

**Issue by zachmullen** [Kitware/tangelohub#106]
The save button is only enabled when the script has changed, but it needs to be pressed in order for input/output changes to be persisted.

**Comment by zachmullen** [comment]
Same applies when editing workflows

**Comment by zackgalbreath** [comment]
Thanks for finding this.  I'll look into this & do my best to fix it soon.

**Comment by jeffbaumes** [comment]
I see this on workflows also - workaround right now is to open the console and execute the command:

```js
$('#save').removeClass('disabled');
```

If it seems like a longer intricate fix, I'd rather have a PR that just keeps the Save button enabled for now.

**Comment by zackgalbreath** [comment]
This was fixed by PR https://github.com/Kitware/tangelohub/pull/108.

For analysis input/outputs we probably could've maintained this feature of enabling & disabling the save button programmatically.  But for workflows there's just too many places where things can change, so it seemed like it would get messy quickly.  Instead we now keep the button enabled at all times, but it turns into a "primary" (blue) button when an analysis has unsaved text in the editor.

**Comment by jeffbaumes** [comment]
Seems like a good solution for now, thanks.
