### ISSUE TITLE
Multistep Workflows currently broken?

### ISSUE THREAD

**Issue by curtislisle** [Kitware/tangelohub#114]
![screen shot 2015-04-29 at 7 50 43 am](https://cloud.githubusercontent.com/assets/2152950/7390288/80056178-ee44-11e4-987c-17b0eff29da4.png)
In the public Arbor instance, "Workflow two-step" in Arbor collection breaks during the InputsView initialization phase (failure at line 55, referredInput is null).  

"Workflow one-step", also in Arbor collection,  works OK.  

My private instance behaves the same as the public instance.

**Comment by jeffbaumes** [comment]
I'm not sure if this type of workflow ever worked. The problem is that the "columnname" input is looking for an input named "inputTable" to use to populate its drop-down menu of columns. But you do not expose "inputTable" in the workflow, instead it's being set from the "Aggregate table by average" output.

If you change the name of the input of "Filter by attribute" to "table" instead of "inputTable" and rebuild the workflow, it should work. This is a hacky workaround for now.

What we really need is a way to let the user update the domain of the "columnname" input to point to another table when building the workflow (an actual workflow input), and warn when the referenced table input will not be found. I think this is possible in the Romanesco spec, but right now we just blindly copy the sub-task input into the workflow input and don't let the user edit it's properties (including its domain). Note that there is no way to know that "Aggregate table by average" will produce a table with the same columns, so there is no way to have this "just work".

**Comment by curtislisle** [comment]
Oh, I see, this situation involves dynamic resolution of column names, etc.  I didn’t realize.  Agreed about the short term solution.  Thanks.
